### ISSUE TITLE
Release/Tag

### ISSUE THREAD

**Issue by jowodo** [ursky/SnapT#2]
Hi, 

I'm trying to install this to a HPC environment with modules[1]. 
I had no luck with conda as mentioned in issue #1, so I cloned from github. 
Could you add releases or tags? This would make it more clear which version is being installed and used. 
This also increases reproducibility. 

Best,
pur

[1] http://modules.sourceforge.net/

**Comment by ursky** [comment]
Good call out. The version is officially v0.4, which you can see if you run `snapt -v`. I just pushed an official release on GitHub, which should be good for tracking.

**Comment by jowodo** [comment]
Awesome! Thanks for the quick reply and resolution!
